services:
  node0:
    build: .
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - CHORD_HOST=node0
    container_name: node0
  
  node1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - CHORD_HOST=node1
      - SOME_NODE_HOST=node0
      - SOME_NODE_PORT=5000
    depends_on:
      - node0
    container_name: node1
  
  node2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - CHORD_HOST=node2
      - SOME_NODE_HOST=node0
      - SOME_NODE_PORT=5000
    depends_on:
      - node0
    container_name: node2
  
  node3:
    build: .
    ports:
      - "5003:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - CHORD_HOST=node3
      - SOME_NODE_HOST=node0
      - SOME_NODE_PORT=5000
    depends_on:
      - node0
    container_name: node3
